### PR TITLE
Update and improve cross-wiki functionality

### PR DESCRIPTION
**Pull request by FR30799386**
Per [this](https://commons.wikimedia.org/wiki/User_talk:FR30799386#mobileUndo) bug report, I have created an updated version of the script which provides improved cross-wiki support. Also updated version number by one.

### CODE REVIEW

**Comment by FR30799386** [comment]
Features added, 
* Added support for RTL writing scripts
* Support for edit summaries in non-English languages
* Improved special page detection

The only con is that the loading time has gone from ~ 2 milliseconds to ~ 600 milliseconds which I'll try and fix on a later date.

**Comment by DannyS712** [comment]
Sorry I haven't gotten to this. Is this the version that is currently on meta? I copied it, see https://en.wikipedia.org/w/index.php?title=User:DannyS712/Undo.js&diff=903890034&oldid=902595233

**Comment by FR30799386** [comment]
This is the one at meta. :)

**Comment by DannyS712** [comment]
Then merged, with the understanding that it has already been updated on enwiki

**Pull request merged**
